general {
  hide_cursor = true
  ignore_empty_input = true
  immediate_render = false
  fail_timeout = 2000
}

animations {
  enabled = false
}

background {
  # path = ~/pictures/wallpapers/wallpaper14.png
  # blur_passes = 3
  # blur_size = 3
  # noise = 0.0211
  color = rgb(29, 32, 33)
}

# time
# label {
#   text = cmd[update:100] echo -e "$TIME"
#   font_family = JetBrainsMono Nerd Font Bold
#   font_size = 16
#
#   color = rgba(235, 219, 178, 1)
#
#   position = 200, 0
#   halign = left
#   valign = bottom
# }

# date & time
label {
  text = cmd[update:100] echo -e "$(date +'%d.%m.%y') - $TIME"
  font_family = JetBrainsMono Nerd Font SemiBold
  font_size = 16

  color = rgba(235, 219, 178, 1)

  position = 0, 20
  halign = center
  valign = bottom
}

# layout
# label {
#   text = cmd[update:100] echo -e "<b>$LAYOUT</b>"
#   font_family = JetBrainsMono Nerd Font Bold
#   font_size = 12
#
#   color = rgba(235, 219, 178, 1)
#
#   position = 25, 25
#   halign = left
#   valign = bottom
# }

input-field {
  size = 100, 60

  dots_size = 0.2
  dots_spacing = 0.2
  dots_center = true

  outline_thickness = 0
  outer_color = rgba(214, 95, 15, 0)
  inner_color = rgba(29, 32, 33, 0)
  rounding = 0

  font_color = rgba(168, 153, 132, 0.6)
  font_family = JetBrainsMono Nerd Font SemiBold
  fade_on_empty = false
  fade_timeout = 0
  hide_input = false

  placeholder_text =
  check_color = rgba(68, 133, 136, 0.0)
  fail_color = rgba(204, 36, 29, 0.0)
  fail_text = <i>$FAIL</i>
  invert_numlock = false

  position = 0, 45
  valign = bottom
  halign = center
}
