general {
  hide_cursor = true
  ignore_empty_input = true
  immediate_render = true
  fail_timeout = 1000
}

animations {
  enabled = false
}

background {
  # path = ~/pictures/wallpapers/
  # blur_passes = 3
  # noise = 0.0411
  color = rgb(28, 28, 28)
}

# label {
#   text = cmd[update:100] echo -e "<i>$(date +'%H:%M\n%d.%m.%y')</i>"
#   font_family = JetBrainsMono Nerd Font Bold
#   color = rgba(230, 230, 200, 0.5)
#   font_size = 35
#
#   position = 0, 5
#   halign = center
#   valign = center
# }

# shape {
#     monitor =
#     size = 250, 125
#     color = rgba(28, 28, 28, 0.9)
#     rounding = 0
#     border_size = 3
#     border_color = rgba(214, 93, 14, 1.0)
#
#     position = 0, 0
#     halign = center
#     valign = center
# }


# input-field {
#   size = 150, 60
#   outline_thickness = 0
#   dots_size = 0.2
#   dots_spacing = 0.2
#   dots_center = true
#   outer_color = rgba(68, 133, 136, 0.6)
#   inner_color = rgba(30, 30, 30, 0.6)
#   font_color = rgba(230, 230, 200, 0.6)
#   font_family = JetBrainsMono Nerd Font Bold
#   fade_on_empty = false
#   fade_timeout = 0
#   placeholder_text = <i></i>
#   hide_input = false
#   rounding = 0
#   check_color = rgba(68, 133, 136, 0.0)
#   fail_color = rgba(204, 36, 29, 0.0)
#   fail_text = <i>$FAIL</i>
#   invert_numlock = false
#   position = 0, 0
#   halign = center
#   valign = center
# }
